#region License Revision: 0 Last Revised: 3/29/2006 8:21 AM
/******************************************************************************
Copyright (c) Microsoft Corporation.  All rights reserved.


This file is licensed under the Microsoft Public License (Ms-PL). A copy of the Ms-PL should accompany this file. 
If it does not, you can obtain a copy from: 

http://www.microsoft.com/resources/sharedsource/licensingbasics/publiclicense.mspx
******************************************************************************/
#endregion // License
//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: NeutralResourcesLanguageAttribute("en-US" , UltimateResourceFallbackLocation.MainAssembly)]
[assembly: AssemblyTitleAttribute("Transition Tester")]
[assembly: AssemblyDescriptionAttribute("Tool for testing Transitionals Transitions")]
[assembly: ComVisibleAttribute(false)]
